### ISSUE TITLE
Ghast sounds

### ISSUE THREAD

**Issue by LegaLT7** [SistrScarlet/LittleMaidReBirth-Fabric#12]
Install the mods and everything seems to work fine but the maids make "Ghast" sounds when you hit them or in general all their sounds are "ghast". I forgot to install something? Did i install something wrong? or is that the default? I think the sounds should be from maids.

**Comment by SistrScarlet** [comment]
(Using DeepL translation)

メイドさんのボイスが、ガストの声になっているのは仕様です。
The maid's voice is the voice of the ghast, which is a specification.

メイドさんのボイスは、サウンドパックを導入すれば変更可能です。
サウンドパックは、".minecraft"(または任意の場所)に生成される、LMMLResourcesフォルダ内に、サウンドパックのzipを置くと導入できます。
The maid's voice can be changed by installing a sound pack.
Sound packs can be installed by placing the sound pack zip file in the LMMLResources folder, which is generated in ".minecraft" (or any location).

導入後の注意点は以下です。
After installation, the following points should be noted

・雇用したメイドさんのインベントリを開き、音符ブロックのボタンからサウンドパックを設定できる
・自然スポーンのメイドさんは、導入されているサウンドパックからランダムに設定されている
・コンフィグから、自然スポーンのメイドさんの無声化と、自然スポーンのメイドさんの声の指定を設定できる
The sound pack can be set by opening the inventory of the hired maid and clicking on the button with the musical note block.
The sound packs for naturally spawned maids are randomly selected from the sound packs installed.
The sound packs for naturally spawned maids are randomly selected from the sound packs installed.

サウンドパック配布場所等はこちら
Click here for Sound Pack distribution locations, etc.
・https://forum.civa.jp/viewtopic.php?f=3&t=57
・https://hashibami.nobody.jp/#modtex
・https://w.atwiki.jp/littlemaidmob/pages/19.html (旧フォーラムの閉鎖に伴いリンク切れ多数。Many links are broken due to the closure of the old forum.)

はしばみさんの「あみたろさん音声uedaカスタム」などがオススメです。
I recommend Hashibami's "Amitaro-san voice ueda custom" and others.



余談ですが、この仕様は、このModのオリジナルである、MMM氏が制作した1.6.2版のLMMに基づいたものです。
声がガストというのは奇妙ではありますが、これはこれでカワイイと私は思います。思え。
As a side note, this specification is based on the 1.6.2 version of LMM, the original version of this mod, created by MMM.
It is odd that the voice is ghast, but this is kawaii in my opinion. Think.
